### ISSUE TITLE
Correct incorrect party dates in meta data

### ISSUE THREAD

**Issue by MansMeg** [welfare-state-analytics/riksdagen-corpus#156]
Also see:
https://github.com/welfare-state-analytics/riksdagen-corpus/issues/149

- [x] Add start date and end date in our party affiliation csv-file @rbbby 
- [x] Fix order so that dates are last
- [x] Check so that month and day is not imputed in the dates

**Comment by salgo60** [comment]
FYI: I have seen in "[Tvåkammarriksdagen 1867-1970](https://libris.kb.se/bib/498955)" some oddities that one person has one party affiliation that has no dates and the next has dates....

**Comment by MansMeg** [comment]
I updated the issues so we focus on just getting the dates in the party affiliation csv file.
