### ISSUE TITLE
Separate protocol and corpus files

### ISSUE THREAD

**Issue by ninpnin** [welfare-state-analytics/riksdagen-corpus#227]
Currently, the protocol files include both _teiHeader_ elements ([example](https://github.com/welfare-state-analytics/riksdagen-corpus/blob/main/corpus/protocols/1922/prot-1922--ak--10.xml#L3)), that contain corpus metadata, as well as _TEI_ elements ([example](https://github.com/welfare-state-analytics/riksdagen-corpus/blob/main/corpus/protocols/1922/prot-1922--ak--10.xml#L31)), that include both the protocol level metadata and the actual protocol.

To reduce redundancy, duplicate errors and file sizes, it would be good to have those things separate.

The corpus files could be on the year-chamber level, eg. prot-1924--fk.xml:
```xml
<teiCorpus xmlns="http://www.tei-c.org/ns/1.0" xmlns:xi="http://www.w3.org/2001/XInclude">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>Riksdagens Protokoll 1924 – Första Kammaren</title>
      </titleStmt>
    </fileDesc>
    <!-- rest of the corpus metadata -->
  </teiHeader>
  <xi:include href="./1924/prot-1924--fk--1.xml"/>
  <xi:include href="./1924/prot-1924--fk--2.xml"/>
  <!-- rest of the protocol links--> 
</teiCorpus>
```

While the protocol files would be similar to how they are now, just without the corpus metadata

```xml
<TEI xmlns="http://www.tei-c.org/ns/1.0">
  <teiHeader>
    <fileDesc>
      <titleStmt>
        <title>Riksdagens Protokoll 1924 – Första Kammaren – Nr 1</title>
      </titleStmt>
    </fileDesc>
    <!-- rest of the protocol metadata -->
  </teiHeader>
  <text>
    <front>
      <div type="preface">
        <head>prot-1924--fk--1</head>
        <docDate when="1924-01-07">1924-01-07</docDate>
      </div>
    </front>
    <body>
      <div>
        <pb facs="https://betalab.kb.se/prot-1924--fk--1/prot_1924__fk__1-000.jp2/_view"/>
        <note xml:id="i-A7G7PedF1hRJqzKAbxmMJW">
          RIKSDAGENS PROTOKOLL.
        </note>
        <!-- rest of the protocol -->
      </div>
    </body>
 </TEI>
```

## TODO

- [x] Write code to convert old parlaclarin files to do this ([commit](https://github.com/welfare-state-analytics/riksdagen-corpus/commit/13d38213d312dd4988992ca94e9dca6612e3a7e6))
- [x] Adjust pipeline.py to do this on new files
- [x] Run the conversion on all data
- [x] Adjust tests to new data structure

**Comment by ninpnin** [comment]
I made some changes to protocol_files.py . Now we would get three corpus files, namely prot-ak.xml, prot-fk.xml and prot-ek.xml, with 5000-8000 protocols each

**Comment by ninpnin** [comment]
@BobBorges can we close this? We have run the conversion and the tests pass (though not merged to main yet?). Does pipeline.py still generate the old format? Does it matter?

**Comment by BobBorges** [comment]
pipeline is not adjusted to this.

I have some other edits to make to pipeline relating to curation of newly acquired protocols at the end of last year, so I will get to them all at once.
